name: Docker Image CI

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: pic4ser-kubernetes/pic4ser-python

jobs:
  deploy:
    name: "Deploy Docker Image"
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern=v{{version}},value=${{ github.ref_name }}
            type=semver,pattern=v{{major}}.{{minor}},value=${{ github.ref_name }}
            type=semver,pattern=v{{major}},value=${{ github.ref_name }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
